Fix compile error introduced by rev 1.205 : control.c(6220) : error C2084: function 'U32 stsi_capabilit y(REGS *)' already has a body
git-svn-id: svn://svn.hercules-390.org/hercules/trunk@3230 969364d3-6d58-4e41-9446-b7e21338ea1b